### PR TITLE
remove some bugs

### PR DESCRIPTION
**Pull request by GuiTaek**
Hello, the repository wasn't working for me in the state that this repository is in. I have used octave in windows. Running the command
```octave data_extracting.m```
didn't work without the changes but mostly worked with the changes. I'm not sure though, if the reason, that it's not working for me is the octave in windows though. I fixed some trailing "'"-s, a missing end and two probably wrong function calls

### CODE REVIEW

**Comment by 28286575show** [comment]
您好！您的邮件已经收到，谢谢！

**Comment by ktekeli** [comment]
Hello, thank you. I have tested your changes in MATLAB, but it didn't work.

**Comment by 28286575show** [comment]
您好！您的邮件已经收到，谢谢！

**Comment by GuiTaek** [comment]
Hi thanks for testing, I guess this means your code works in Matlab and my code works in Octave. Maybe I didn't understand your code, but I was pretty sure about some of the errors being small oversights that wouldn't make your code work. Very weird. Maybe our both codes don't work because I have some small oversights, too?

**Comment by GuiTaek** [comment]
Ahh just looked at the pull request, could it be, that the ' means something like transpose? I know this didn't worked on octave but maybe on Matlab it has a meaning? Like transpose? I'm sorry, I'm not that fit in matlab and to be honest not even in octave.

**Comment by ktekeli** [comment]
Yes, exactly. That means transpose in MATLAB. Thanks for your time for editing these codes in Octave. I will update this repository as soon as possible.

**Comment by GuiTaek** [comment]
Thank you, too for the time!

**Pull request closed without merging**
